# Generated by Django 2.1.2 on 2018-10-09 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.URLField()),
                ('api_version', models.IntegerField(choices=[(0, 'NA'), (1, 'GUTMA_V1'), (2, 'GUTMA_V2')], verbose_name='version')),
                ('authentication', models.IntegerField(choices=[(0, 'None'), (1, 'JWT'), (2, 'TOKEN')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=140)),
                ('query_type', models.IntegerField(choices=[(0, 'Regular'), (1, 'Privileged')], default=0)),
                ('query_parameter', models.IntegerField(choices=[(0, 'Operator ID'), (1, 'RPAS ID'), (2, 'Pilot ID')], default=0)),
                ('state', models.IntegerField(choices=[(0, 'PENDING'), (1, 'RECEIVED'), (2, 'STARTED'), (3, 'SUCCESS'), (4, 'RETRY'), (5, 'IGNORED')], default=0, verbose_name='state')),
                ('results', models.TextField(default='Querying registries, this will populate once all queries are complete..')),
                ('logs', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
