# Generated by Django 2.1.7 on 2019-03-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='credentials',
            field=models.TextField(default=''),
        ),
    ]
